---
title: "Task 4"
author: "Taylor Medina"
date: "10/23/2021"
output: html_document
---
### Setup
```{r setup, include=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 3)

# load in packages
library(tidyverse)
library(here)
library(kableExtra)
library(plotly)
library(janitor)
library(lubridate)

```


```{r, warning = FALSE, message = FALSE}

napl_urchins <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names() %>% 
  mutate(date = ymd(date),
         year = year(date)) %>% 
  filter(year == "2010", 
         common_name == "Purple Urchin",
         site == "NAPL")

napl_urchins_stats <- napl_urchins %>% 
  group_by(treatment) %>% 
  summarize(mean_diameter_cm = mean(size),
            standard_deviation = sd(size),
            sample_size = n())

```


```{r}

napl_urchins_hist <- ggplot(data = napl_urchins,
                            aes(x = size)) +
  geom_histogram(aes(fill = treatment), color = "black", binwidth = 0.5) +
  facet_wrap(~ treatment) +
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) +
  labs(x = "diameter (cm)",
       y = "count")
  

ggplotly(napl_urchins_hist)

```
**Figure 1:**

```{r}

napl_urchins_qq <- ggplot(data = napl_urchins,
                          aes(sample = size)) +
  stat_qq() +
  stat_qq_line(aes(color = treatment)) +
  facet_wrap(~ treatment) +
  theme_classic() 

ggplotly(napl_urchins_qq)

```
**Figure 2:** 


```{r}

napl_urchins_stats %>% 
  kable(col.names = c("Treatment",
                      "Mean Diameter (cm)",
                      "Standard Deviation ()",
                      "Sample Size "),
        caption = "Table 1: Statistical Summary of Purple Urchin Diameters (cm) ") %>% 
  kable_classic(full_width = FALSE)

```

