---
title: "Task 3 - Santa Barbara Urchins"
author: "Taylor Medina"
date: "10/21/2021"
output: html_document
---

**Data:** Reed, D. 2020. SBC LTER: Reef: Long-term experiment: Kelp removal: Urchin size frequency distribution ver 20. Environmental Data Initiative. https://doi.org/10.6073/pasta/5a1e9ef03aa47bd2225c0bb98a02a63b. 

### Setup
```{r setup, include=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 3) # sets sig figs to 3

# Load in packages
library(tidyverse)
library(here)
library(kableExtra)
library(plotly)
library(janitor)
library(lubridate)

```

### Section 1
```{r, message = FALSE}

urchins <- read_csv(here("data", "urchins.csv")) %>% 
  clean_names()

urchins_plot <- ggplot(data = urchins,
       aes(x = size)) +
  geom_histogram(bins = 10, aes(fill = common_name), color = "black") +
  facet_wrap(~ common_name) + # splits plots by species
  xlim(0,15) + # sets x limit to 15 cm
  ylim(0,14000) + # sets y limit to a count of 14000
  scale_fill_manual(values = c("purple","red")) + # specifies colors manually
  theme_classic() +
  labs(x = "urchin diameter (cm)",
       y = "frequency",
       fill = "Common Name") # sets name of legend

ggplotly(urchins_plot)

```
**Figure 1:** Size Distribution of Purple and Red Sea Urchins in Santa Barbara Reefs

```{r}

urchin_stats <- urchins %>% 
  group_by(common_name) %>% 
  summarize(mean_diameter_cm = mean(size, na.rm = TRUE), # calculates mean diameter
            median_diameter_cm = median(size, na.rm = TRUE), # calculates median diameter
            standard_deviation = sd(size, na.rm = TRUE), # calculates standard deviation 
            sample_size = n()) # sample size count

urchin_stats %>% 
  kable(col.names = c("Species", 
                      "Mean Diameter (cm)",
                      "Median Diameter (cm)",
                      "Standard Deviation",
                      "Sample Size"),
        caption = "Table 1: Summary Statistics of Purple and Red Urchins in Santa Barbara Reefs") %>% 
  kable_classic(full_width = FALSE)

```

### Section 2
```{r, message = FALSE}

purple_urchins <- urchins %>% 
  filter(common_name == "Purple Urchin") %>% 
  mutate(date = mdy(date), # converts the date column class from function to date
         year = year(date), # makes a new column splicing the year from the date column
         site_full = case_when( # makes a new column converting the short names to the full names of the sites
           site == "NAPL" ~ "Naples Reef",
           site == "AQUE" ~ "Arroyo Quemado Reef",
           site == "CARP" ~ "Carpinteria Reef",
           site == "MOHK" ~ "Mohawk Reef",
           site == "IVEE" ~ "Isla Vista Reef"))

purple_urchins_stats <- purple_urchins %>% 
  group_by(year,site_full) %>% 
  summarize(count = n()) # generates a count of purple observations by year and site

```

```{r}

purple_urchins_plot <- ggplot(data = purple_urchins_stats,
                              aes(x = year, y = count)) +
  geom_line(aes(color = site_full)) +
  theme_classic() +
  guides(col = guide_legend("Sampling Sites")) +
  labs(x = "year",
       y = "sea urchin count",
       title = "Purple Sea Urchin Populations in Santa Barbara Reefs ") 

ggplotly(purple_urchins_plot)

```
**Figure 2**
